using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;

namespace SmartMeter.Hubs
{
    public class Meter
    {
        // External or connection identifier (e.g. connection id or provided meter id)
        public string ID { get; init; } = string.Empty;

        // readings keyed by Unix milliseconds timestamp generated by the server
        // timestamp -> reading value
        public ConcurrentDictionary<long, double> Readings { get; } = new();

        // Add a reading and return the timestamp used (Unix ms)
        public (long Timestamp, double Value) AddReading(double reading)
        {
            var ts = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
            // store rounded reading (2 dp)
            var rounded = Math.Round(reading, 2);
            Readings.TryAdd(ts, rounded);
            return (ts, rounded);
        }

        public double SumReadings() =>
            Readings.Values.Sum();

        public int ReadingCount => Readings.Count;

        public IReadOnlyDictionary<long, double> Snapshot() =>
            Readings.ToDictionary(kv => kv.Key, kv => kv.Value);
    }
}