// Mocks generated by Mockito 5.4.6 from annotations
// in smart_meter_client/test/mock_hubConn_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:signalr_netcore/hub_connection.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStreamController_0<T> extends _i1.SmartFake
    implements _i2.StreamController<T> {
  _FakeStreamController_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HubConnection].
///
/// See the documentation for Mockito's code generation for more information.
class MockHubConnection extends _i1.Mock implements _i3.HubConnection {
  MockHubConnection() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get serverTimeoutInMilliseconds =>
      (super.noSuchMethod(
            Invocation.getter(#serverTimeoutInMilliseconds),
            returnValue: 0,
          )
          as int);

  @override
  int get keepAliveIntervalInMilliseconds =>
      (super.noSuchMethod(
            Invocation.getter(#keepAliveIntervalInMilliseconds),
            returnValue: 0,
          )
          as int);

  @override
  _i2.Stream<_i3.HubConnectionState> get stateStream =>
      (super.noSuchMethod(
            Invocation.getter(#stateStream),
            returnValue: _i2.Stream<_i3.HubConnectionState>.empty(),
          )
          as _i2.Stream<_i3.HubConnectionState>);

  @override
  set serverTimeoutInMilliseconds(int? value) => super.noSuchMethod(
    Invocation.setter(#serverTimeoutInMilliseconds, value),
    returnValueForMissingStub: null,
  );

  @override
  set keepAliveIntervalInMilliseconds(int? value) => super.noSuchMethod(
    Invocation.setter(#keepAliveIntervalInMilliseconds, value),
    returnValueForMissingStub: null,
  );

  @override
  set baseUrl(String? url) => super.noSuchMethod(
    Invocation.setter(#baseUrl, url),
    returnValueForMissingStub: null,
  );

  @override
  _i2.Future<void>? start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>?);

  @override
  _i2.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Stream<Object?> stream(String? methodName, List<Object>? args) =>
      (super.noSuchMethod(
            Invocation.method(#stream, [methodName, args]),
            returnValue: _i2.Stream<Object?>.empty(),
          )
          as _i2.Stream<Object?>);

  @override
  _i2.StreamController<Object?> streamControllable(
    String? methodName,
    List<Object>? args,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#streamControllable, [methodName, args]),
            returnValue: _FakeStreamController_0<Object?>(
              this,
              Invocation.method(#streamControllable, [methodName, args]),
            ),
          )
          as _i2.StreamController<Object?>);

  @override
  _i2.Future<void> send(String? methodName, {List<Object>? args}) =>
      (super.noSuchMethod(
            Invocation.method(#send, [methodName], {#args: args}),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<Object?> invoke(String? methodName, {List<Object>? args}) =>
      (super.noSuchMethod(
            Invocation.method(#invoke, [methodName], {#args: args}),
            returnValue: _i2.Future<Object?>.value(),
          )
          as _i2.Future<Object?>);

  @override
  void on(String? methodName, _i3.MethodInvocationFunc? newMethod) =>
      super.noSuchMethod(
        Invocation.method(#on, [methodName, newMethod]),
        returnValueForMissingStub: null,
      );

  @override
  void off(String? methodName, {_i3.MethodInvocationFunc? method}) =>
      super.noSuchMethod(
        Invocation.method(#off, [methodName], {#method: method}),
        returnValueForMissingStub: null,
      );

  @override
  void onclose(_i3.ClosedCallback? callback) => super.noSuchMethod(
    Invocation.method(#onclose, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  dynamic onreconnecting(_i3.ReconnectingCallback? callback) =>
      super.noSuchMethod(Invocation.method(#onreconnecting, [callback]));

  @override
  dynamic onreconnected(_i3.ReconnectedCallback? callback) =>
      super.noSuchMethod(Invocation.method(#onreconnected, [callback]));
}
